version: 0.2
phases:
  build:
    commands:
      - export BUCKET=codebuildbucket4
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file output-template.yml
artifacts:
  type: zip
  files:
    - template.yml
    - output-template.yml
    
    #testgitstep7